#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Mar 20 12:50:43 2024

@author: kokoro
"""

import matplotlib.pyplot as plt
import numpy as np
import warnings
from scipy.signal import find_peaks

#This is a code which fits a polynomial onto data and peak pick the polynomial and tell you the frequecy and the numbe rof the peak present in the data.


def peak(lowlim,upperlim,filename, n):
    data1=[]
#selecting a section of a peak
#importing the data

    limits = [lowlim,upperlim]     
    data = np.loadtxt(filename, dtype=float, delimiter=',',skiprows=1)
#Select the frequecy values between the limits and make a list of those values that meets the condition.
    for i in range(0, len(data)): 
        if limits[0] <= data[i,0] <= limits[1]:
            data1.append(data[i])
            
            #turn the data into an array from a turple
    data2=np.array(data1)
#slice the x and FFT from the array
    x=data2[:,0]
    FFT=data2[:,1]
#nomarlise the Amplitude spectral density
    y=(FFT/max(FFT))  
#set polynomial p(x) of degree n that is a best fit (in a least-squares sense) for the data in y
#calculate the polynomial that fits our data.
    z=np.polyfit(x,y,n) 

#plotting high order polynomials 
    with warnings.catch_warnings():
        warnings.simplefilter('ignore', np.RankWarning)
        p = np.poly1d(z)

#find the maximum and the mnimum value of x to set values for xp and calcuate the values in the polynomial fit    
    xpl=min(data[:,0])
    xph=max(data[:,0])
#setting  the x values for the polynomial y values p
    xp = np.linspace(xpl,xph,1000)
    fit = p(xp)
    # xpmod=[]
    # fitmod =[]
    # for i in range(0, len(data)): 
    #         if limits[0] <= xp[i] <= limits[1]:
    #             xpmod.append(xp[i])
    #             fitmod.append(fit[i])
            
 
#peak pick
#index each peaks calculatedby find_peaks

    id = find_peaks(fit)
    ind = id[0]

    pk_freq = xp[ind]
    pk_amp = fit[ind]

            
#plot
    fig, ax = plt.subplots()
    ax.scatter(pk_freq, pk_amp)
    plt.plot(x, y, 'x')
    plt.plot(xp, fit,'-')
    plt.ylim(0,1.1)
    plt.xlim(limits[0],limits[1])
    plt.xlabel('Frequency /GHz')
    plt.ylabel('Amplitude spectral density/ Arb. unit')


#for i, txt in enumerate(pk_freq):
    for i in range(len(pk_freq)):    
        if pk_freq[i]<=(limits[1]-5):
            ax.annotate(i+1,(pk_freq[i], pk_amp[i]+0.01),xytext=(pk_freq[i]-1,pk_amp[i]+ 0.18+0.002*i**2),va='top',
            arrowprops=dict(arrowstyle="-", facecolor='black'))

    plt.show()
    index=[]
    pk_frq_l=[]
    for i, txt in enumerate(pk_freq):
        index.append(i+1)
        pk_frq_l.append(pk_freq[i])
        pk_list_T=np.array([index, pk_frq_l])
        pk_list=np.transpose(pk_list_T)
    
    print('File names:',filename,
          'The set values for the analysis are following;',
          'The frequency range is',limits,' degree of polynomial is',n, 
          'The equation of the fit is ',p,
          'Within the limits the peak frequency is',pk_list,'GHz')
    return xp, fit, x,y,p,limits,pk_list

def trial_p(filename, n):
    data = np.loadtxt(filename, dtype=float, delimiter=',',skiprows=1)
    x=data[:,0]
    FFT=data[:,1]
    #nomarlise the Amplitude spectral density
    y=(FFT/max(FFT))  
  
    z=np.polyfit(x,y,n) 

    #plotting high order polynomials 
    with warnings.catch_warnings():
        warnings.simplefilter('ignore', np.RankWarning)
        p = np.poly1d(z)

    #find the maximum and the mnimum value of x to set values for xp and calcuate the values in the polynomial fit    
    xpl=min(x)
    xph=max(x)
    #setting  the x values for the polynomial y values p
    xp = np.linspace(xpl,xph,100000)
    fit = p(xp)
    
    plt.plot(x,y,'x')
    plt.plot(xp,fit,'-')
    plt.xlabel('Frequency /GHz')
    plt.ylabel('Amplitude spectral density/ Arb. unit')
    plt.title('trial')
    plt.ylim(-0.1,1.1)
    

    

